security:
    always_authenticate_before_granting: true
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: bcrypt
            cost: 15

    role_hierarchy:
        ROLE_ADMIN:       [ ROLE_USER ]
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ADMIN_CONFIG, ROLE_ALLOWED_TO_SWITCH, ROLE_FILEMANAGER ]
        ROLE_ROOT:        [ ROLE_SUPER_ADMIN ]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        admin:
            anonymous: ~
            context: monolith_cms
            logout_on_user_change: true
            pattern: ^/%admin_path%
            form_login:
                check_path: /%admin_path%/login_check
                login_path: /%admin_path%/
                default_target_path: /%admin_path%/
            logout:
                path: /%admin_path%/logout
            remember_me:
                secret: "%secret%"
                name: MONOLITH_REMEMBER_ME
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~
        main:
            anonymous: ~
            context: monolith_cms
            logout_on_user_change: true
            pattern: ^/
            form_login:
                # csrf_provider: form.csrf_provider # @deprecated in 3.x
                check_path: /%user_path%/login_check
                login_path: /%user_path%/
                default_target_path: /%user_path%/
            logout:
                path: /%user_path%/logout
            remember_me:
                secret: "%secret%"
                name: MINOLITH_REMEMBER_ME
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~

#    access_control:
#        - { path: ^/_assistant/, roles: ROLE_ADMIN }
#        - { path: ^/%admin_path%/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/%admin_path%/resetting$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/%admin_path%/system/config/, role: ROLE_ADMIN_CONFIG }
#        - { path: ^/%admin_path%, roles: ROLE_ADMIN }
#        - { path: ^/efconnect, role: ROLE_FILEMANAGER }
#        - { path: ^/elfinder, role: ROLE_FILEMANAGER }
#        - { path: ^/%user_path%/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/%user_path%/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/%user_path%/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/%user_path%, roles: ROLE_USER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
