site.images:
    resource: '@SmartMediaBundle/Resources/config/routing.yml'
    prefix: /_media/

site:
    resource: '@SiteBundle/Resources/config/routing.yml'
    prefix: /

cms_api:
    resource: routing_api.yml
    prefix: /%cms_api%/

cms_admin:
    resource: routing_admin.yml
    prefix: /%admin_path%/

elfinder:
    resource: '@FMElfinderBundle/Resources/config/routing.yml'

# @todo решить вопрос с загрузкой файлов в формах
#genemu_base64:
#    resource: '@GenemuFormBundle/Resources/config/routing/base64.xml'
#genemu_image:
#    resource: '@GenemuFormBundle/Resources/config/routing/image.xml'
#genemu_upload:
#    resource: '@GenemuFormBundle/Resources/config/routing/upload.xml'

cms_admin_site_switch_selected:
    path: /__cms_site_switch_selected/
    methods: POST
    defaults:
        _controller: CMSBundle:Admin:switchSelectedSite

cms_frontend_run:
    path: /{slug}
    methods: GET
    defaults:
        _controller: CMSBundle:FrontEnd:run
        slug: ''
    requirements:
        slug: '.+'

cms_frontend_post_processor:
    path: /{slug}
    methods: POST
    defaults:
        _controller: CMSBundle:FrontEnd:post
        slug: ''
    requirements:
        slug: '.+'

# @todo Эти маршруты нужны для генерации ссылок к модулям с учетом пути, куда они подключены.
cms_modules:
    resource: .
    type: modules_enabled

fos_user_security:
    resource: '@FOSUserBundle/Resources/config/routing/security.xml'
    prefix: /%user_path%

fos_user_profile:
    resource: '@FOSUserBundle/Resources/config/routing/profile.xml'
    prefix: /%user_path%

fos_user_register:
    resource: '@FOSUserBundle/Resources/config/routing/registration.xml'
    prefix: /%user_path%/register

fos_user_resetting:
    resource: '@CMSBundle/Resources/config/routing/fosuser_resetting.xml'
    prefix: /%user_path%/resetting

fos_user_change_password:
    resource: '@FOSUserBundle/Resources/config/routing/change_password.xml'
    prefix: /%user_path%
